// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelTransaction(ctx context.Context, arg CancelTransactionParams) (CancelTransactionRow, error)
	CheckAccountBalance(ctx context.Context, arg CheckAccountBalanceParams) (CheckAccountBalanceRow, error)
	CompleteTransaction(ctx context.Context, id pgtype.UUID) (CompleteTransactionRow, error)
	CreateBalanceHistoryRecord(ctx context.Context, arg CreateBalanceHistoryRecordParams) (CreateBalanceHistoryRecordRow, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	FailTransaction(ctx context.Context, arg FailTransactionParams) (FailTransactionRow, error)
	GetAccountBalanceHistory(ctx context.Context, arg GetAccountBalanceHistoryParams) ([]CoreAccountBalanceHistory, error)
	GetAccountByAccountNumber(ctx context.Context, accountNumber string) (CoreAccount, error)
	// Account-related queries for transaction service
	GetAccountByID(ctx context.Context, id pgtype.UUID) (CoreAccount, error)
	GetBalanceHistoryByDateRange(ctx context.Context, arg GetBalanceHistoryByDateRangeParams) ([]CoreAccountBalanceHistory, error)
	GetBalanceHistoryByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]CoreAccountBalanceHistory, error)
	GetPendingTransactions(ctx context.Context, limit int32) ([]GetPendingTransactionsRow, error)
	GetRecentTransactionsByAccount(ctx context.Context, arg GetRecentTransactionsByAccountParams) ([]GetRecentTransactionsByAccountRow, error)
	GetTransactionByID(ctx context.Context, id pgtype.UUID) (GetTransactionByIDRow, error)
	GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (GetTransactionByIdempotencyKeyRow, error)
	GetTransactionSummaryByAccount(ctx context.Context, accountID pgtype.UUID) (GetTransactionSummaryByAccountRow, error)
	GetTransactionsByAccount(ctx context.Context, arg GetTransactionsByAccountParams) ([]GetTransactionsByAccountRow, error)
	GetTransactionsByAccountAndType(ctx context.Context, arg GetTransactionsByAccountAndTypeParams) ([]GetTransactionsByAccountAndTypeRow, error)
	GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]GetTransactionsByDateRangeRow, error)
	GetTransactionsByReference(ctx context.Context, referenceID pgtype.Text) ([]GetTransactionsByReferenceRow, error)
	GetTransactionsByStatus(ctx context.Context, arg GetTransactionsByStatusParams) ([]GetTransactionsByStatusRow, error)
	UpdateTransactionMetadata(ctx context.Context, arg UpdateTransactionMetadataParams) (UpdateTransactionMetadataRow, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (UpdateTransactionStatusRow, error)
}

var _ Querier = (*Queries)(nil)
