// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckAccountBalance(ctx context.Context, arg CheckAccountBalanceParams) (CheckAccountBalanceRow, error)
	GetAccountBalanceHistory(ctx context.Context, arg GetAccountBalanceHistoryParams) ([]CoreAccountBalanceHistory, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (CoreAccount, error)
	GetAccountByNumber(ctx context.Context, accountNumber string) (CoreAccount, error)
	GetAccountSummary(ctx context.Context, id pgtype.UUID) (GetAccountSummaryRow, error)
	GetAccountsByBalanceRange(ctx context.Context, arg GetAccountsByBalanceRangeParams) ([]GetAccountsByBalanceRangeRow, error)
	GetAccountsByCurrency(ctx context.Context, arg GetAccountsByCurrencyParams) ([]CoreAccount, error)
	GetAccountsByStatus(ctx context.Context, arg GetAccountsByStatusParams) ([]CoreAccount, error)
	GetAccountsWithLowBalance(ctx context.Context, arg GetAccountsWithLowBalanceParams) ([]GetAccountsWithLowBalanceRow, error)
	ValidateAccountForTransaction(ctx context.Context, arg ValidateAccountForTransactionParams) (ValidateAccountForTransactionRow, error)
}

var _ Querier = (*Queries)(nil)
